name: Swift Lint
on: [pull_request, workflow_dispatch]
jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macOS-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Xcode 15.4
        run: sudo xcode-select -switch /Applications/Xcode_15.1.app
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict
