name: Unit Tests and Coverage
on:
  push:
    branches: [main]
    paths:
      - "Sources/**"
      - ".github/workflows/tests.yaml"
      
  pull_request:
    branches: [main]
    paths:
      - "Sources/**"
      - ".github/workflows/tests.yaml"
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    env:
     GITHUB_TOKEN: ${{ secrets.ACTIONS_API_TOKEN }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
          
      - name: Install LLVM
        run: |
          sudo apt-get install -y llvm clang lcov
          
      - name: Run Unit Tests
        run: swift test --enable-code-coverage --verbose

      - name: Create Coverage Data
        run: |
          mkdir -p coverage
          llvm-profdata merge -sparse .build/debug/codecov/*.profraw -o merged.profdata
          llvm-cov export --format=lcov --instr-profile=merged.profdata .build/debug/kounty-apiPackageTests.xctest > coverage/lcov.info
    
      - name: Validate Minimum Coverage
        uses: mattpolzin/swift-codecov-action@0.7.5
        with:
         MINIMUM_COVERAGE: 0
         INCLUDE_TESTS: 'true'
         
      - name: Post Test coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
         lcov-file: coverage/lcov.info
