name: Unit Tests and Coverage
on:
  push:
    branches: [main]
    paths:
      - "Sources/**"
      - ".github/workflows/tests.yaml"
      
  pull_request:
    branches: [main]
    paths:
      - "Sources/**"
      - ".github/workflows/tests.yaml"
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    env:
     GITHUB_TOKEN: ${{ secrets.ACTIONS_API_TOKEN }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
          
      - name: Install LLVM
        run: |
          sudo apt-get install -y llvm clang lcov
          
      - name: Run Unit Tests
        run: swift test --enable-code-coverage --verbose

      - name: Create Coverage Data
        run: |
          mkdir -p coverage
          
          llvm-profdata merge -sparse .build/debug/codecov/*.profraw -o merged.profdata       
          llvm-cov export --format=lcov \
          --ignore-filename-regex="APIS|Core|DataAccess|Services|.build" \
          --instr-profile=merged.profdata \
          .build/debug/kounty-apiPackageTests.xctest > coverage/app-full-lcov.info

          if [ -f "coverage/app-full-lcov.info" ]; then
            echo "LCOV report generated successfully at coverage/app-full-lcov.info"

            # Filter the report to only include sections related to files under APIs/AuthenticationApi/Sources
            awk '/^SF:.*\/Sources/{keep=1} /^SF:/&&!/Sources/{keep=0} {if(keep) print}' coverage/app-full-lcov.info > coverage/app-lcov.info

            # Check if the filtered report was generated successfully
            if [ -f "coverage/app-lcov.info" ]; then
                echo "Filtered LCOV report created at coverage/app-lcov.info"
            else
                echo "Failed to create filtered LCOV report."
                exit 1
            fi
          else
            echo "Failed to generate LCOV report."
            exit 1
          fi
    
      - name: Validate Minimum Coverage
        uses: mattpolzin/swift-codecov-action@0.7.5
        with:
         MINIMUM_COVERAGE: 0
         INCLUDE_TESTS: 'true'
         
      - name: Post Test coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
         lcov-file: coverage/lcov.info
